-- NO escribir BEGIN/COMMIT ni CREATE EXTENSION en este archivo.
CREATE FUNCTION sl_build(regclass, text)
RETURNS bigint AS 'MODULE_PATHNAME', 'sl_build'
LANGUAGE C VOLATILE STRICT PARALLEL UNSAFE;

CREATE FUNCTION sl_search(integer)
RETURNS tid AS 'MODULE_PATHNAME', 'sl_search'
LANGUAGE C VOLATILE STRICT PARALLEL UNSAFE;

CREATE FUNCTION sl_insert(integer, tid)
RETURNS boolean AS 'MODULE_PATHNAME', 'sl_insert'
LANGUAGE C VOLATILE STRICT PARALLEL UNSAFE;

CREATE FUNCTION sl_range(integer, integer)
RETURNS SETOF tid AS 'MODULE_PATHNAME', 'sl_range'
LANGUAGE C VOLATILE STRICT PARALLEL UNSAFE;

CREATE FUNCTION sl_clear()
RETURNS void AS 'MODULE_PATHNAME', 'sl_clear'
LANGUAGE C VOLATILE PARALLEL UNSAFE;

CREATE FUNCTION sl_count()
RETURNS bigint AS 'MODULE_PATHNAME', 'sl_count'
LANGUAGE C VOLATILE PARALLEL UNSAFE;
